"""posts and user tables edited

Revision ID: 2f7e32801072
Revises: 5c519ef68a43
Create Date: 2023-04-02 17:32:30.025760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7e32801072'
down_revision = '5c519ef68a43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('disease_type', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('tissue_sample_collection_method', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('paint_type', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('zoom_amount', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('patient_age', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('patient_gender', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('patient_other_disease', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('clinical_diagnosis', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('pathological_diagnosis', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('radiology_report', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('pathologic_description', sa.String(), nullable=False))
    op.drop_column('posts', 'content')
    op.drop_column('posts', 'title')
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    op.add_column('users', sa.Column('user_bio', sa.String(), nullable=True))
    op.drop_column('users', 'user_photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'user_bio')
    op.drop_column('users', 'profile_image')
    op.add_column('posts', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'pathologic_description')
    op.drop_column('posts', 'radiology_report')
    op.drop_column('posts', 'pathological_diagnosis')
    op.drop_column('posts', 'clinical_diagnosis')
    op.drop_column('posts', 'patient_other_disease')
    op.drop_column('posts', 'patient_gender')
    op.drop_column('posts', 'patient_age')
    op.drop_column('posts', 'zoom_amount')
    op.drop_column('posts', 'paint_type')
    op.drop_column('posts', 'tissue_sample_collection_method')
    op.drop_column('posts', 'disease_type')
    # ### end Alembic commands ###
