"""add photo url to user

Revision ID: 5c519ef68a43
Revises: 21373ba98193
Create Date: 2023-04-02 16:12:41.677329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c519ef68a43'
down_revision = '21373ba98193'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_photo')
    # ### end Alembic commands ###
